language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  # we only run pylint on latest python
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then pip install -r requirements-lock; fi
script:
  - python cute.py test
