language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - pip install -r requirements-lock.txt --ignore-requires-python
script:
  - python cute.py test
