language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - python -c "import sys;exit(sys.version_info >= (3, 5))" || pip install -r requirements-lock.txt
script:
  - python cute.py test
