language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python -m pip install -U pip
  - pip install -e .
  # https://github.com/pypa/pip/issues/6371
  - pip install -r requirements-lock.txt --python-version 3.8 --no-deps
script:
  - python cute.py test
