language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python -m pip install -U pip
  - pip install -e .
  - xargs -a requirements-lock.txt pip install || true
script:
  - python cute.py test
